USE [master]
GO

/****** Object:  Database [TRADE_PRICING]    Script Date: 11/11/2020 12:51:04 AM ******/
CREATE DATABASE [TRADE_PRICING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TRADE_PRICING', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.APPDATA\MSSQL\DATA\TRADE_PRICING.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TRADE_PRICING_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.APPDATA\MSSQL\DATA\TRADE_PRICING_log.ldf' , SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TRADE_PRICING] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TRADE_PRICING].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TRADE_PRICING] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET ARITHABORT OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TRADE_PRICING] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TRADE_PRICING] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TRADE_PRICING] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TRADE_PRICING] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TRADE_PRICING] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TRADE_PRICING] SET  MULTI_USER 
GO

ALTER DATABASE [TRADE_PRICING] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TRADE_PRICING] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TRADE_PRICING] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TRADE_PRICING] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TRADE_PRICING] SET  READ_WRITE 
GO


